INSERT INTO EMPLOYEE VALUES(1,'IT','Matej', 1000);
INSERT INTO EMPLOYEE VALUES(2,'Design','Sara', 2000);
INSERT INTO EMPLOYEE VALUES(3,'Actor','Anamarija', 3000);
INSERT INTO DEPARTMENT VALUES(1,'IT','CroTeam', 1);
INSERT INTO DEPARTMENT VALUES(2,'Design','Vogue', 2);
INSERT INTO DEPARTMENT VALUES(3,'Actor','WarnerBros',3 );
